### ISSUE TITLE
Allow changing button sizing of timers

### ISSUE THREAD

**Issue by ghost** [dubrowgn/micro-timer#7]
Can we get a way to change the button size? For some reason the button sizes on my phone shows it as huge and looks weird in the app. It makes having multiple times look cluttered. This is having 4 timers as reference Button sizes are huge https://imgur.com/gallery/aHD5nmS

That or have a built in compact mode?

Phone: Galaxy S10
Android version: 12

**Comment by dubrowgn** [comment]
Yeah, that's not expected. The button widths should be automatic, but I didn't get it working the other week. It looks like this caused the text to wrap on your phone. The height is automatic though, so they look huge.

I'll take another look when I get a minute.

**Comment by dubrowgn** [comment]
I got my hands on an S10+, and it looks like the Samsung device is using a different background drawable that doesn't have any inherent margins, while the stock Android button background drawable does. The way I'm handling margins works in stock Android, but produces overly large buttons on Samsung.

I'm not entirely sure what to do about it. One solution is to define my own button background drawable so buttons render consistently across devices. I haven't decided if that's a good idea or not yet. Surely other people use buttons in their apps.
I wonder how this is dealt with in general.

**Comment by dubrowgn** [comment]
I'm directly attaching the screenshot for future reference:
![oversized buttons](https://github.com/dubrowgn/micro-timer/assets/1294253/eed99d08-84e4-4052-9aad-32718fcbcaf1)

**Comment by dubrowgn** [comment]
This should be fixed in c1df397f25aa791a36298a88f639428606cd837e and a6d4aac75eb44c5dc7255e1eb8d83ebe04b4d4cb.

**Comment by dubrowgn** [comment]
This is released in [v1.9](https://github.com/dubrowgn/micro-timer/releases/tag/v1.9). You can install it from the releases page, or it should show up in F-Droid in a few days. Feel free to re-open this issue if you continue to experience this problem.
